version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'sq1-blog'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
  redis:
    image: redis
    ports:
      - "6379:6379"
    depends_on:
      - db
  app:
    build: .
    image: 'sq1-blog'
    depends_on:
      - redis
    ports:
      - 8080:80
